// runtime.cpp — implements runtime.hpp: device/queue/library bring-up,
// pipeline cache, tracked shared-mode buffers, planner, telemetry, and the
// serial-encoder CommandBatch (v0.1 sync protocol, plan §6).
// SPDX-License-Identifier: Apache-2.0

#include "runtime.hpp"

#include <dispatch/dispatch.h>

#include <atomic>
#include <cstdlib>
#include <cstring>
#include <mutex>
#include <unordered_map>

#include <Foundation/Foundation.hpp>

#include "../kernels/mg_params.h"

// Embedded metallib (generated by cmake/EmbedMetallib.cmake). MG_METALLIB
// env overrides with an on-disk library for the dev JIT loop.
extern "C" {
extern const unsigned char mg_metallib_data[];
extern const size_t mg_metallib_size;
}

namespace mg {
namespace {

std::string ns_error_str(NS::Error* e) {
  if (!e) return "(no NSError)";
  NS::String* d = e->localizedDescription();
  const char* c = d ? d->utf8String() : nullptr;
  return c ? std::string(c) : "(no description)";
}

// RAII autorelease pool (metal-cpp objects returned autoreleased — e.g.
// NS::String::string — live until the pool is released).
struct Pool {
  NS::AutoreleasePool* p;
  Pool() : p(NS::AutoreleasePool::alloc()->init()) {}
  ~Pool() { p->release(); }
  Pool(const Pool&) = delete;
  Pool& operator=(const Pool&) = delete;
};

class MetalBuffer final : public Buffer {
 public:
  MetalBuffer(MTL::Buffer* b, std::size_t bytes) : b_(b), bytes_(bytes) {}
  ~MetalBuffer() override { b_->release(); }
  void* data() override { return b_->contents(); }
  std::size_t byte_size() const override { return bytes_; }
  MTL::Buffer* mtl() override { return b_; }

 private:
  MTL::Buffer* b_;  // owned (+1 from newBuffer)
  std::size_t bytes_;
};

class HeapBuffer final : public Buffer {
 public:
  HeapBuffer(void* p, std::size_t bytes) : p_(p), bytes_(bytes) {}
  ~HeapBuffer() override { std::free(p_); }
  void* data() override { return p_; }
  std::size_t byte_size() const override { return bytes_; }
  MTL::Buffer* mtl() override { return nullptr; }

 private:
  void* p_;
  std::size_t bytes_;
};

thread_local RunInfo t_last_run;

}  // namespace

// ---------------------------------------------------------------------------
// Runtime
// ---------------------------------------------------------------------------

struct Runtime::Impl {
  MTL::Device* device = nullptr;        // owned; nullptr => CPU-only mode
  MTL::CommandQueue* queue = nullptr;   // owned
  MTL::Library* library = nullptr;     // owned
  BufferPtr dummy;
  std::mutex pso_mutex;
  std::unordered_map<std::string, MTL::ComputePipelineState*> psos;
  std::atomic<int> mode{static_cast<int>(ExecMode::autom)};
};

Runtime::Runtime() : impl_(std::make_unique<Impl>()) {
  Pool pool;
  if (!env_flag("MG_FORCE_CPU"))
    impl_->device = MTL::CreateSystemDefaultDevice();
  if (!impl_->device) {
    if (env_flag("MG_REQUIRE_GPU"))
      throw Error(ErrorCode::no_gpu,
                  "MG_REQUIRE_GPU=1 but no Metal device is available");
  } else {
    impl_->queue = impl_->device->newCommandQueue();
    if (!impl_->queue)
      throw Error(ErrorCode::internal, "failed to create MTLCommandQueue");
    NS::Error* err = nullptr;
    const char* lib_path = std::getenv("MG_METALLIB");
    if (lib_path && *lib_path) {
      NS::String* s = NS::String::string(lib_path, NS::UTF8StringEncoding);
      impl_->library = impl_->device->newLibrary(NS::URL::fileURLWithPath(s),
                                                 &err);
    } else {
      dispatch_data_t data =
          dispatch_data_create(mg_metallib_data, mg_metallib_size, nullptr,
                               DISPATCH_DATA_DESTRUCTOR_DEFAULT);
      impl_->library = impl_->device->newLibrary(data, &err);
      dispatch_release(data);
    }
    if (!impl_->library)
      throw Error(ErrorCode::internal,
                  "failed to load metallib: " + ns_error_str(err));
  }
  impl_->dummy = alloc(16, "mg_dummy");
}

Runtime::~Runtime() {
  if (!impl_) return;
  for (auto& kv : impl_->psos)
    if (kv.second) kv.second->release();
  impl_->dummy.reset();
  if (impl_->library) impl_->library->release();
  if (impl_->queue) impl_->queue->release();
  if (impl_->device) impl_->device->release();
}

Runtime& Runtime::instance() {
  static Runtime rt;
  return rt;
}

bool Runtime::has_gpu() const { return impl_->device != nullptr; }
MTL::Device* Runtime::device() const { return impl_->device; }
MTL::CommandQueue* Runtime::queue() const { return impl_->queue; }

MTL::ComputePipelineState* Runtime::pipeline(const char* kernel_name,
                                             bool weighted, bool uniform_p) {
  if (!impl_->device)
    throw Error(ErrorCode::internal,
                std::string("pipeline '") + kernel_name +
                    "' requested in CPU-only mode");
  std::string key = std::string(kernel_name) + (weighted ? "|w1" : "|w0") +
                    (uniform_p ? "u1" : "u0");
  {
    std::lock_guard<std::mutex> lk(impl_->pso_mutex);
    auto it = impl_->psos.find(key);
    if (it != impl_->psos.end()) return it->second;
  }
  Pool pool;
  // Both constants are set every time; kernels that do not declare one
  // simply ignore it (cache key still includes both flags).
  MTL::FunctionConstantValues* fcv =
      MTL::FunctionConstantValues::alloc()->init();
  bool w = weighted, u = uniform_p;
  fcv->setConstantValue(&w, MTL::DataTypeBool, NS::UInteger(MG_FC_WEIGHTED));
  fcv->setConstantValue(&u, MTL::DataTypeBool, NS::UInteger(MG_FC_UNIFORM_P));
  NS::Error* err = nullptr;
  MTL::Function* fn = impl_->library->newFunction(
      NS::String::string(kernel_name, NS::UTF8StringEncoding), fcv, &err);
  fcv->release();
  if (!fn)
    throw Error(ErrorCode::internal, std::string("kernel '") + kernel_name +
                                         "' not found: " + ns_error_str(err));
  err = nullptr;
  MTL::ComputePipelineState* pso =
      impl_->device->newComputePipelineState(fn, &err);
  fn->release();
  if (!pso)
    throw Error(ErrorCode::internal,
                std::string("pipeline creation failed for '") + kernel_name +
                    "': " + ns_error_str(err));
  std::lock_guard<std::mutex> lk(impl_->pso_mutex);
  auto [it, inserted] = impl_->psos.emplace(key, pso);
  if (!inserted) {  // lost a build race; keep the cached one
    pso->release();
    return it->second;
  }
  return pso;
}

uint32_t Runtime::exec_width(MTL::ComputePipelineState* p) const {
  return static_cast<uint32_t>(p->threadExecutionWidth());
}

BufferPtr Runtime::alloc(std::size_t bytes, const char* label) {
  const std::size_t n = bytes < 4 ? 4 : bytes;  // Metal rejects 0-byte buffers
  if (impl_->device) {
    Pool pool;
    MTL::Buffer* b =
        impl_->device->newBuffer(n, MTL::ResourceStorageModeShared);
    if (!b)
      throw Error(ErrorCode::out_of_memory,
                  std::string("buffer allocation failed: ") +
                      (label ? label : "(unlabeled)"));
    if (label)
      b->setLabel(NS::String::string(label, NS::UTF8StringEncoding));
    std::memset(b->contents(), 0, n);  // zero-init is contractual
    return std::make_shared<MetalBuffer>(b, n);
  }
  void* p = std::calloc(1, n);
  if (!p)
    throw Error(ErrorCode::out_of_memory,
                std::string("host allocation failed: ") +
                    (label ? label : "(unlabeled)"));
  return std::make_shared<HeapBuffer>(p, n);
}

BufferPtr Runtime::dummy() const { return impl_->dummy; }

void Runtime::set_mode(ExecMode m) {
  impl_->mode.store(static_cast<int>(m), std::memory_order_relaxed);
}

ExecMode Runtime::mode() const {
  return static_cast<ExecMode>(impl_->mode.load(std::memory_order_relaxed));
}

ExecPath Runtime::plan(uint64_t stored_edges) const {
  const ExecMode m = mode();
  if (m == ExecMode::gpu) {
    if (!has_gpu())
      throw Error(ErrorCode::no_gpu,
                  "execution mode 'gpu' but no Metal device is available");
    return ExecPath::gpu;
  }
  if (m == ExecMode::cpu) return ExecPath::cpu;
  return (has_gpu() && stored_edges >= e_gpu_min()) ? ExecPath::gpu
                                                    : ExecPath::cpu;
}

uint64_t Runtime::e_gpu_min() const {
  long v = env_long("MG_E_GPU_MIN", 1000000);
  return v < 0 ? 0 : static_cast<uint64_t>(v);
}

void Runtime::record_run(const RunInfo& info) { t_last_run = info; }
RunInfo Runtime::last_run() const { return t_last_run; }

// ---------------------------------------------------------------------------
// CommandBatch
// ---------------------------------------------------------------------------

struct CommandBatch::Impl {
  NS::AutoreleasePool* pool = nullptr;
  MTL::CommandBuffer* cmd = nullptr;      // retained for the batch lifetime
  MTL::ComputeCommandEncoder* enc = nullptr;  // pool-owned; null when closed
  bool committed = false;

  MTL::ComputeCommandEncoder* ensure_encoder() {
    if (committed)
      throw Error(ErrorCode::internal, "CommandBatch used after commit");
    if (!enc) {
      enc = cmd->computeCommandEncoder();
      if (!enc)
        throw Error(ErrorCode::internal, "failed to create compute encoder");
    }
    return enc;
  }
};

namespace {

void bind_common(MTL::ComputeCommandEncoder* enc,
                 MTL::ComputePipelineState* pso, const void* params,
                 std::size_t params_size,
                 std::initializer_list<Buffer*> buffers) {
  enc->setComputePipelineState(pso);
  enc->setBytes(params, params_size, 0);  // buffer(0) is always the params
  NS::UInteger idx = 1;
  for (Buffer* b : buffers) enc->setBuffer(b->mtl(), 0, idx++);
}

}  // namespace

CommandBatch::CommandBatch(Runtime& rt) : impl_(std::make_unique<Impl>()) {
  if (!rt.has_gpu())
    throw Error(ErrorCode::internal,
                "CommandBatch constructed in CPU-only mode");
  impl_->pool = NS::AutoreleasePool::alloc()->init();
  impl_->cmd = rt.queue()->commandBuffer();
  if (!impl_->cmd) {
    impl_->pool->release();
    impl_->pool = nullptr;
    throw Error(ErrorCode::internal, "failed to create MTLCommandBuffer");
  }
  impl_->cmd->retain();
}

CommandBatch::~CommandBatch() {
  if (!impl_) return;
  if (impl_->enc) {
    impl_->enc->endEncoding();
    impl_->enc = nullptr;
  }
  if (impl_->cmd) impl_->cmd->release();
  if (impl_->pool) impl_->pool->release();
}

void CommandBatch::dispatch(MTL::ComputePipelineState* pso, const void* params,
                            std::size_t params_size,
                            std::initializer_list<Buffer*> buffers,
                            uint32_t threadgroups, uint32_t threads_per_tg) {
  if (threadgroups == 0) return;  // empty grid: encoding would be a no-op
  MTL::ComputeCommandEncoder* enc = impl_->ensure_encoder();
  bind_common(enc, pso, params, params_size, buffers);
  enc->dispatchThreadgroups(MTL::Size(threadgroups, 1, 1),
                            MTL::Size(threads_per_tg, 1, 1));
}

void CommandBatch::dispatch_indirect(MTL::ComputePipelineState* pso,
                                     const void* params,
                                     std::size_t params_size,
                                     std::initializer_list<Buffer*> buffers,
                                     Buffer* args,
                                     std::size_t args_byte_offset,
                                     uint32_t threads_per_tg) {
  MTL::ComputeCommandEncoder* enc = impl_->ensure_encoder();
  bind_common(enc, pso, params, params_size, buffers);
  enc->dispatchThreadgroups(args->mtl(), args_byte_offset,
                            MTL::Size(threads_per_tg, 1, 1));
}

void CommandBatch::break_encoder() {
  if (impl_->enc) {
    impl_->enc->endEncoding();
    impl_->enc = nullptr;
  }
}

void CommandBatch::commit_and_wait() {
  if (impl_->committed)
    throw Error(ErrorCode::internal, "CommandBatch committed twice");
  break_encoder();
  impl_->committed = true;
  impl_->cmd->commit();
  impl_->cmd->waitUntilCompleted();
  if (impl_->cmd->status() == MTL::CommandBufferStatusError ||
      impl_->cmd->error())
    throw Error(ErrorCode::internal,
                "command buffer failed: " + ns_error_str(impl_->cmd->error()));
}

}  // namespace mg
